#! /bin/bash

set -euo pipefail
IFS=$'\n\t'
set -x

PROTOC=${PROTOC:-$KUDU_HOME/thirdparty/installed/uninstrumented/bin/protoc}
PROTO_INCLUDE=${PROTO_INCLUDE:-$KUDU_HOME/thirdparty/src/protobuf-2.6.1/src}

PROTOS="
client/client.proto
common/common.proto
common/wire_protocol.proto
util/compression/compression.proto
consensus/opid.proto
consensus/replica_management.proto
fs/fs.proto
master/master.proto
rpc/rpc_header.proto
security/token.proto
tablet/tablet.proto
tserver/tserver.proto
tserver/tserver_service.proto
"

for PROTO in $PROTOS;
do
  $PROTOC --rust_out src/ --proto_path $KUDU_HOME/src/ --proto_path $PROTO_INCLUDE $KUDU_HOME/src/kudu/$PROTO
done

$PROTOC --rust_out src/ --proto_path $KUDU_HOME/src/ --proto_path $PROTO_INCLUDE $KUDU_HOME/src/kudu/consensus/metadata.proto
mv src/metadata.rs src/consensus_metadata.rs

$PROTOC --rust_out src/ --proto_path $KUDU_HOME/src/ --proto_path $PROTO_INCLUDE $KUDU_HOME/src/kudu/tablet/metadata.proto
mv src/metadata.rs src/tablet_metadata.rs

sed -i.bak 's/metadata/consensus_metadata/' src/wire_protocol.rs
rm src/wire_protocol.rs.bak

sed -i.bak 's/metadata/tablet_metadata/' src/tablet.rs
rm src/tablet.rs.bak

sed -i.bak 's/metadata::Tablet/tablet_metadata::Tablet/' src/master.rs
sed -i.bak 's/metadata::Raft/consensus_metadata::Raft/' src/master.rs
sed -i.bak 's/metadata::Consensus/consensus_metadata::Consensus/' src/master.rs
rm src/master.rs.bak
